version: "3.8"
#
# Services definitions
#
services:
  app:
    image: kooldev/php:8.1-nginx
    container_name: doctor-docs-app
    ports:
      - "${KOOL_APP_PORT:-80}:80"
    environment:
      ASUSER: "${KOOL_ASUSER:-0}"
      UID: "${UID:-0}"
    volumes:
      - .:/app:delegated
    networks:
      - kool_local
      - kool_global
    depends_on:
      - docs-database
  docs-database:
    image: postgres:13-alpine
    container_name: doctor-docs-database
    ports:
      - "127.0.0.1:${KOOL_DATABASE_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: "${DB_DATABASE-database}"
      POSTGRES_USER: "${DB_USERNAME-user}"
      POSTGRES_PASSWORD: "${DB_PASSWORD-pass}"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - database:/var/lib/postgresql/data:delegated
    networks:
      - kool_local
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "$DB_DATABASE", "-U", "$DB_USERNAME" ]
#
# Networks definitions
#
networks:
  kool_local:
  kool_global:
    external: true
    name: "${KOOL_GLOBAL_NETWORK:-kool_global}"
volumes:
  cache:
  database:

